### ISSUE TITLE
Internal Constructor on Square9.CustomNode.Settings

### ISSUE THREAD

**Issue by scott-malyon** [Square9Softworks/custom-workflow-nodes#1]
Hi there,

This is probably what will be the first of many questions and thoughts about Custom Nodes.

Is there a good reason for the internal constructor on the Settings class?
I ask as this makes testing my settings loading and parsing a little tricky
I have interfaced it and mocked my own variant for now, but I was just curious as it seems a simple class with little dependency on anything

**Comment by bbanet** [comment]
Scott,

We are not really sure what you are trying to achieve.  If you can provide some specifics about what you are trying to do, it might help.  The working theory is you are trying to load model data into the settings class?

**Comment by scott-malyon** [comment]
Hi,

Yes I was attempting to populate a `Settings` class with some test data, but I cannot initialise it with a `Dictionary<string, Setting>` due to the constructor being internal.

This `Settings` class would then be used in testing.

For example I have generic `WorkflowNodeConfigLoader<T>` class which takes `Settings` and config model for a particular node then maps and gets the settings based on the config model's property names and their types.

**Comment by bbanet** [comment]
There is no reason why the constructor couldn't be made public.  We can add it to the list for inclusion in a future release.  With that said, you can not test Custom Nodes in an isolated/stand alone fashion like you were able to do with Call Assembly nodes, so the feeling is that the practical use of doing something like this is fairly limited.
