### ISSUE TITLE
S9 Notation

### ISSUE THREAD

**Issue by scott-malyon** [Square9Softworks/custom-workflow-nodes#2]
Good afternoon.

Two question regarding Custom Nodes and S9 Notation.

1. Are there plans implement the type-ahead/auto-completion for S9 Notation in Custom Node as it is for the Built-In Nodes?
2. Will implementers have to write their own parser for S9 Notation. I am assuming if 1 is implemented you would want developers to follow the existing scheme for notation?

**Comment by bbanet** [comment]
1. Yes, this is a high value feature, but is complicated and was too much to make the rev 1 cut of this featue.
2. S9 notation is parsed prior to sending it into the node's run methods, so no, you are not expected to parse this.
