### ISSUE TITLE
Obtaining the Process Field type

### ISSUE THREAD

**Issue by scott-malyon** [Square9Softworks/custom-workflow-nodes#3]
Hi,

I am looking for a good way to work out the type (single-value, multi-value, table) of the process fields in a custom node. 

Tables are fine, they have an explicit Type of 5

But beyond that it gets messy, I have tried getting the value using the two different methods
```
Process.Properties.GetSingleValue(name)
Process.Properties.GetMultiValue(name)
```
Then wrapping these in try/catches (which I know is awful code) but GetSingleValue() does not throw if used against an MV field
I also tried calling each one on each field and checking the returned value for null, but null is an acceptable value.

This is some test code showing my current "solution". Which works, but this requires that the MV field is set to a value prior to the call to GetMultiValue() else that will throw

```
        private string GetPropType(string name)
        {
            if (Process.Properties.GetPropertyByName(name).Type == 5)
            {
                return "table";
            }

            try
            {
                Process.Properties.GetMultiValue(name);
                return "multi";
            }
            catch (Exception)
            {
                return "single";
            }
        }
```

I do not like this for several reasons:

1. Each property will be accessed twice unless it is a table
2. It uses exceptions for flow
3. The MV field will require a value set by a Set Process Field node for it not to throw and assumed to be single

Any better ideas?

**Comment by scott-malyon** [comment]
Me again,

I realised I was being silly and re-worked it a little to remove two of my reservations

```
        private string GetPropType(string name)
        {
            dynamic property = Process.Properties.GetPropertyByName(name);

            if (property.Type == 5)
            {
                return "table";
            }

            if (property.MValue != null)
            {
                return "multi";
            }

            return "single";
        }
```

This is better but:
1. Assumes single if not one of the others, which is probably fair.
2. Still requires the MV be initialised manually by a Set Process Field node. If this initialisation were done as part of creating the process my world would be simpler.

**Comment by scott-malyon** [comment]
More ramblings,

What I am trying to achieve gets a little more complex with table fields as these require knowledge of the fields that are used for the column names. Were the table fields initialised in some fashion but with no contents then as with initialised MV Fields I could work out their make-up/type

I did go down the route of accessing the field catalogue as all this information is there, for capture this is fine but for search catalogues there are multiple and names need not be unique across those catalogues.

So I ended up having to put more information into the node's config so that the designer has to explicitly tell me if a field is MV or table. Which will work but is more prone to mistakes by the designer.

If you do have any thoughts I would like to hear them.

**Comment by bbanet** [comment]
You might want to look at the dynamic process object.  

http://knowledge.square-9.com:8090/display/CN/GetProcessDynamic+Method

There are not helper methods for the items you are seeking, but the dynamic process would get you access to the entire data set.  This should include the table fields object when table data is present.

**Comment by scott-malyon** [comment]
I assume you mean Process.Properties which is the collection of the items obtained via Process.Properties.GetPropertyByName(name) ?

I did look around the object but did not see anything else relevant.

If so then the same it has the same issue for me - All field types are null unless they are set during the process. Which is fine for inserting data using templating or whatever and then reading data out but not if I want to insert data into a field which has not been touched. As I cannot know how and what to set on it if all I have is its name.

For example, my view of a table field, one untouched by the process.

```
{
	"ID": 8,
	"Name": "A Table Field",
	"Type": 5,
	"SystemProperty": false,
	"Value": null,
	"MValue": null,
	"Confidence": 0,
	"SourceType": 0,
	"PortalID": 0,
	"DBID": 0,
	"FieldID": 1179,
	"TableFields": null,
	"Left": 0,
	"Top": 0,
	"Right": 0,
	"Bottom": 0,
	"Page": 0,
	"TemplateProperty": false
}
```

Technically I can know it is a table field due to the type, but I do not know its columns, nor could I do this with MV as they have no specific type.

Unless I am missing something?

**Comment by bbanet** [comment]
The process object has a GetProcessDynamic method.  This will get you the entire object of the process from the database.  This is what you should inspect for more detail.
